version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3050:80
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - .env
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client-test:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - .env
      - NODE_ENV=development
    command: [ "npm", "run", "test" ]
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - .env
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
