//RECIPES
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";
export const FETCH_RECIPES_LOAD = "FETCH_RECIPES_LOAD";
export const FETCH_RECIPE_DETAILS_SUCCESS = "FETCH_RECIPE_DETAILS_SUCCESS";
export const FETCH_RECIPE_DETAILS_FAIL = "FETCH_RECIPE_DETAILS_FAIL";
export const FETCH_RECIPE_DETAILS_LOAD = "FETCH_RECIPE_DETAILS_LOAD";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_FAIL = "CREATE_RECIPE_FAIL";
export const CREATE_RECIPE_LOAD = "CREATE_RECIPE_LOAD";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_FAIL = "UPDATE_RECIPE_FAIL";
export const UPDATE_RECIPE_LOAD = "UPDATE_RECIPE_LOAD";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_FAIL = "DELETE_RECIPE_FAIL";
export const DELETE_RECIPE_LOAD = "DELETE_RECIPE_LOAD";
