apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipal-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipal-client
  template:
    metadata:
      labels:
        app: recipal-client
    spec:
      containers:
        - name: recipal-client
          image: registry.digitalocean.com/docrnuagirprod/recipal-client:latest
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              memory: "50Mi"
              cpu: "10m"
      imagePullSecrets:
        - name: docrnuagirprod
