apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipal-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipal-server
      environment: production
  template:
    metadata:
      namespace: recipal
      labels:
        app: recipal-server
    spec:
      containers:
        - name: recipal-server
          image: registry.digitalocean.com/docrnuagirprod/recipal-server:latest
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              memory: "50Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: docrnuagirprod
