name: Server
on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
      - 'nginx/**'
      - 'kubernetes/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build the server docker image
        run: docker build ./server --file ./server/Dockerfile --tag ${{ secrets.DOCR_URL }}/recipal-server:latest --tag ${{ secrets.DOCR_URL }}/recipal-server:${{ github.sha }}
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Push the server docker latest image
        run: docker push ${{ secrets.DOCR_URL }}/recipal-server:latest
      - name: Push the server docker commit SHA image
        run: docker push ${{ secrets.DOCR_URL }}/recipal-server:${{ github.sha }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_DOKS_NAME }}
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DIGITALOCEAN_DOKS_KUBECONFIG }}
        id: set-context
      - name: Deploy the Kubernetes components
        run: kubectl apply -f kubernetes
      - name: Create the server deployment
        run: kubectl set image deployments/recipal-server-deployment recipal-server=${{ secrets.DOCR_URL }}/recipal-server:${{ github.sha }} --record
